### ISSUE TITLE
[Feature] Refactor Object.assign to defu

### ISSUE THREAD

**Issue by Baroshem** [colbyfayock/cloudinary-util#126]
# **Feature Request**

In several places in the code, `Object.assign` is used to set default values for configuration.

At Nuxt (and more specifically in the unjs organization) we have a package called `defu` that is widely used in Nuxt modules and framework.

It is a more efficient default assigner imho and I think it could be useful to add here.

I have an article about it https://dev.to/jacobandrewsky/assigning-default-properties-efficiently-with-defu-2in2

https://github.com/unjs/defu

In some more advanced cases you may want to create a custom merging strategy like the one in the NuxtSecurity for merging arrays:

```ts
import { createDefu } from 'defu'

export const defuReplaceArray = createDefu((obj, key, value) => {
  if (Array.isArray(obj[key]) || Array.isArray(value)) {
    obj[key] = value
    return true
  }
})
```

**Comment by colbyfayock** [comment]
hey @Baroshem did you want to work on this one?

**Comment by Baroshem** [comment]
Yes, please assign me and I will work on it (probably next week) :)

**Comment by Baroshem** [comment]
Hey @colbyfayock 

I tried implementing it but before I push the code I wanted to ask you if there it actually makes sense.

I looked through the code and managed to only find one place where this defu is useful:
```ts
  if ( typeof text === 'string' ) {
    applyOverlay({
      text: defu(DEFAULT_TEXT_OPTIONS, {
        text
      })
    })
  } else if ( typeof text === 'object' ) {
    applyOverlay({
      text: Object.assign({}, DEFAULT_TEXT_OPTIONS, text)
    })
  }
```

The second Object.assign wasn't replaced because it assigns a text here if it is in an object while defu by default works in merging nested properties. So only the first option was replaced.

Not sure if its worth adding a new dependency just to accomodate one place in the code. When I first created this issue I think there were more places. Maybe they were refactored or maybe I just didn't look good enough :D 

Also, I had some issues with updating the pnpm.lock as it was resulting in changing 5000 lines there (probably an issue with a different version of pnpm.

I am awaiting your comments :)

**Comment by colbyfayock** [comment]
yeah i tend to think right now probably makes sense not to, only because its just an additional dependency like you say

thanks for the heads up on pnpm, i think i need to update my project locally, ive tried to look for a good way to manage different pnpm versions but seems like theres not a great solution

**Comment by Baroshem** [comment]
Thanks for the comment Colby.

Should we close this issue as not planned?
