### ISSUE TITLE
Fix TS Errors

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/cloudinary-util#2]
There are a few instances that I'm currently using `// @ts-expect-error` due to not knowing how to solve these TS issues

These should be cleaned up.

**Comment by LarsEjaas** [comment]
It isn't too difficult. Let me give you an example:

If you go to `packages > loader > src > plugins > overlays.ts` line 36 and forward where you pass data into the applyOverlay function. You have the codesection:

```
applyOverlay({
      // @ts-expect-error
      text: {
        ...DEFAULT_TEXT_OPTIONS,
        text
      }
    })
  } else if ( typeof text === 'object' ) {
    applyOverlay({
      text: {
        ...DEFAULT_TEXT_OPTIONS,
        ...text
      }
    })
  }
  ```
  
  If you hover DEFAULT_TEXT_OPTIONS the `fontSize` attribute takes a number (or undefined as the attribute is optional) but in the ApplyOverlaySettingsText interface you type the optional `fontsize` attribute as string.

**Comment by LarsEjaas** [comment]
Generally it is easiest to start reading the typescript errors from the bottom up, but it takes a bit of getting used to. Generally I think that is where most people are struggling with TypeScript,

**Comment by colbyfayock** [comment]
okay here's another one:

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/loader/src/plugins/overlays.ts#L179

```
      if ( typeof text === 'object' ) {
        (Object.keys(text) as Array<keyof typeof text>).forEach(key => {
          // @ts-expect-error
          if ( !qualifiersText[key] ) return;
```

i have a few configuration objects set up that define what qualifiers are available. in this code, i'm checking to see if it exists, and if it does, i do something later

im getting errors when i use this pattern in this file

**Comment by LarsEjaas** [comment]
Hmm... this one is a bit more tricky. One thing I would start with: If you go into /constants/qualifiers

```
export const primary = {
  aspectRatio: {
    qualifier: 'ar'
  },
  crop: {
    qualifier: 'c'
  },
  gravity: {
    qualifier: 'g'
  },
  height: {
    qualifier: 'h'
  },
  width: {
    qualifier: 'w'
  },
} as const
``` 

try hovering the different parameters like eg. qualifier: 'w' - they are all typed as string. That could be anything. Then try adding the `as const` as I did.

**Comment by LarsEjaas** [comment]
In typeScript you really can't use strings to index objects. Example:

const parameter:string = 'ar'.

const example = object[parameter] will give you a type error.

So using the `as const` will help you and make your strings way more specific.

**Comment by LarsEjaas** [comment]
> okay here's another one:
> 
> https://github.com/colbyfayock/cloudinary-util/blob/main/packages/loader/src/plugins/overlays.ts#L179
> 
> ```
>       if ( typeof text === 'object' ) {
>         (Object.keys(text) as Array<keyof typeof text>).forEach(key => {
>           // @ts-expect-error
>           if ( !qualifiersText[key] ) return;
> ```
> 
> i have a few configuration objects set up that define what qualifiers are available. in this code, i'm checking to see if it exists, and if it does, i do something later
> 
> im getting errors when i use this pattern in this file

As pointed out above this way you will effectively try to index the qualifiersText with string - that won't work. Try this instead:

```
(Object.keys(options).forEach((key:keyof typeof options) => {
      
      if ( !qualifiersPrimary[key] ) return;
      // @ts-expect-error
      const { qualifier } = qualifiersPrimary[key];
      primary.push(`${qualifier}_${options[key]}`);
    }));
```

**Comment by colbyfayock** [comment]
that got me closer, then it got me thinking about that list of definitions and i found this:

https://stackoverflow.com/a/62650775/844780

and it got most of that solved!

only some oddities i fix:

``` 
   if ( hasPosition ) {
      (Object.keys(position) as Array<keyof typeof position>).forEach((key) => {
        if ( !qualifiersPosition[key as string] ) return;

        const { qualifier } = qualifiersPosition[key as string];
```
the `key as string` which wondering why i need that from https://github.com/colbyfayock/cloudinary-util/blob/main/packages/loader/src/plugins/underlays.ts#L94

which interestingly i needed to fix in that file, but not overlays.ts

and trying to now solve this one:

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/loader/src/plugins/overlays.ts#L187

where any instance of `text[key]` gives me:

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/1045274/215865783-14f6706a-f259-4b31-8a64-02aa0c45018d.png">

**Comment by LarsEjaas** [comment]
```
 if ( hasPosition ) {
      Object.keys(position).forEach((key:keyof typeof position) => {
       
```
try this instead. Try hovering key now: They are no longer just typed as `string`.

**Comment by colbyfayock** [comment]
is this what you mean?

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1045274/215866681-a70ef63f-1575-425a-a238-2582753ff93d.png">

gives me an erro after removing the `as string` when doing that

**Comment by LarsEjaas** [comment]
We actually have to go a step backwards here to //General options. If you hover key in line 75:

`const { qualifier } = qualifiersPrimary[key];` you will see that typescript really do not understand that we are returning if the key is not in the qualifiersPrimary object - and worse yet: qualifier is typed as `any` 🤪.

This is actually something missing a lot in TypeScript - hopefully it will be solved soon. Until that you need to use something called a Type Predicate - this is a small helper function:

```
function objHasKey<T>(obj: T, key: PropertyKey): key is keyof T {
  return Object.prototype.hasOwnProperty.call(obj, key);
}
```

And now we can do:
```
 // Gemeral options

    (Object.keys(options).forEach((key:keyof typeof options) => {
      
      if ( !(objHasKey(qualifiersPrimary, key)) ) return;
      
      const { qualifier } = qualifiersPrimary[key];
      primary.push(`${qualifier}_${options[key]}`);
    }));
```  
Now try hovering key: TypeScript now knows that key can only be "crop" | "height" | "width".

And *magically* qualifier is now typed as string.

You can read about type predicates here: https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates

Happy coding!

**Comment by colbyfayock** [comment]
awesome thanks @LarsEjaas
