### ISSUE TITLE
[Feature] constructCloudinaryUrl only produces a url to an image, missing video

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/cloudinary-util#6]
_Migrated from https://github.com/colbyfayock/next-cloudinary/issues/115_

# **Bug Report**
Trying to use constructCloudinaryUrl to build a url to a video

## **Describe the bug**
I have this code:
```
const videoSrc = constructCloudinaryUrl({
        options: {
            src: myUrl,
            width: 300
        },
    });
```
This url produced is: 
`https://res.cloudinary.com/my_cloud/image/upload/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

As you can see the `image` part of the above path is wrong, it should instead be `video`. I thought passing `deliveryType: "video"` might solve it but that produces: `https://res.cloudinary.com/my_cloud/image/video/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

## **Expected behaviour**
It should produce: `https://res.cloudinary.com/my_cloud/video/upload/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

Perhaps its this line in the source: 
```
return cldImage.setDeliveryType((options == null ? void 0 : options.deliveryType) || 'upload').format((options == null ? void 0 : options.format) || 'auto').delivery("q_" + ((options == null ? void 0 : options.quality) || 'auto')).toURL({
```

**Comment by alexTayanovsky** [comment]
Just stumbled upon the same issue ☹️

**Comment by colbyfayock** [comment]
been tied up with other priorities, will try to get to this soon! thanks for your patience

**Comment by colbyfayock** [comment]
hey @alexTayanovsky should now be available on the latest!

let me know if you run into any issues. Also if there are any particular transformations that aren't currently included that would be helpful to use
