### ISSUE TITLE
[Feature] Add new plugin for Generative Replace

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/cloudinary-util#68]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

URL Loader should support Generative Replace: https://cloudinary.com/blog/generative-replace-object-replacement-with-ai

## **Describe the solution you'd like**

In my mind I'm thinking the prop can be `replace`. The tricky part is there isn't a single string that can be used unless we use delimiters which i think doesnt make sense for this API, instead, I'm thinking examples such as:

```
replace={['apple', 'banana']}
```

Which would apply a transformation like:

```
e_gen_replace:from_apple;to_banana
```

we could also support object syntax which may help support additional future features:

```
replace={{
 from: 'apple',
 to: 'banana',
}}
```

Feedback would be great on this.

Please check out the notes and limitations in the docs: https://cloudinary.com/documentation/transformation_reference#e_gen_replace

One for instance is that the transformation must be the first in the chain, meaning it should be added to the transformation array similar to background removal: https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/lib/cloudinary.ts#L26

Please add support for this plugin as well as tests

**Comment by michaeljolley** [comment]
@colbyfayock, using object syntax makes a lot more sense to me. Especially considering there's a 3rd, optional parameter `preserve-geometry`. 

I'd love to take this one on and sneak it in as a last commit for Hacktoberfest.

**Comment by colbyfayock** [comment]
all yours! i was thinking supporting multiple syntaxes would be nice to make it easy for the different use cases, the simpler the use case the simpler the syntax, but can see what you come up with

**Comment by michaeljolley** [comment]
I'm technically wrapping up the object syntax version. No problem to add an array option as well. Want me to add it?

**Comment by colbyfayock** [comment]
yeah let's do it!
