### ISSUE TITLE
[Bug] Fix generic types

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/cloudinary-util#74]
# **Bug Report**

## **Describe the bug**

From Josh Goldberg (thanks:

Right now, `PluginSettings` declares that all objects satisfying it have an `options` property that can be ***any*** of: `AssetOptions`, `ImageOptions`, `VideoOptions`:

```tsx
export interface PluginSettings {
  options: AssetOptions | ImageOptions | VideoOptions;
}
```

But that’s not really accurate. Some plugins assume they’ll be given options of a particular type.

For these cases, you could make `PluginSettings` *******generic******* so that it takes in a *type parameter*. Doing so allows places using the interface to customize the interface - in this case, telling it a more specific type for `options`:

```tsx
type AllOptions = AssetOptions | ImageOptions | VideoOptions;

export interface PluginSettings<Options extends AllOptions = AllOptions>{
  options: Options;
}
```

- `extends`: says that `Options` must extend from `AllOptions`(i.e. be one of those ones)
- `=`: if the place using `PluginSettings` doesn’t provide an explicit `Options`, default to `AllOptions`

```tsx
export function plugin(props: PluginSettings<ImageOptions>) {
  const { cldAsset, options } = props;
  const { fillBackground } = options;
  // No longer necessary: as ImageOptions ✨
```

**Comment by Insidiae** [comment]
I'd like to work on this one!

**Comment by colbyfayock** [comment]
All yours!
